import {expect,test,Page} from "@playwright/test";
const ids=["component-base","component-shoulder-servo","component-upper-arm","component-elbow-servo","component-forearm","component-end-effector","component-controller","component-power"];
const labels=["Robotic arm base","Shoulder servo","Upper arm link","Elbow servo","Forearm link","Conceptual gripper","ESP32 controller","Low-voltage power"];
const positions=[[0,0,9],[0,0,35],[32,0,105],[64,0,170],[35,0,225],[5,0,282],[100,35,10],[100,-35,12]];
const parts=ids.map((semanticId,i)=>({semanticId,label:labels[i],subsystem:i===1||i===3?"actuation":i>5?"electronics":"structure",parentAssembly:"robotic-arm",representationSource:"conceptual procedural model",dimensions:i===2?[28,145,18]:i===4?[24,125,16]:[50,35,22],assembledTransform:{position:positions[i]},explodedTransform:{position:[positions[i][0]+i*12,positions[i][1],positions[i][2]+i*10]},verificationState:"conceptual"}));
const assembly={parts,connectors:[],relationships:ids.slice(1).map((id,i)=>({from:ids[i],to:id,type:i%2?"mechanical":"control"}))};
const graph={project_id:"project-arm",entities:[{id:"project-arm",kind:"project",name:"Conceptual Servo Robotic Arm"},...parts.map(p=>({id:p.semanticId,kind:"component",name:p.label,parent_id:`subsystem-${p.subsystem}`,metadata:{}})),{id:"net-shoulder-control",kind:"connection",name:"Shoulder control",metadata:{semantic_type:"electrical_net",role:"control-signal",terminals:[{componentId:"component-controller",interfaceId:"signal"},{componentId:"component-shoulder-servo",interfaceId:"signal"}],displayStyle:{color:"#d88ac9"}}}],relationships:[]};
const schematic=[
 {type:"schematic_component",schematic_component_id:"schematic_M1",source_component_id:"source_M1",center:{x:0,y:0},size:{width:1.5,height:.8},symbol_name:"boxresistor_right",symbol_display_value:"M1",is_box_with_pins:true,rotation:0,aura_semantic_id:"component-shoulder-servo"},
 {type:"schematic_port",schematic_port_id:"schematic_port_1",schematic_component_id:"schematic_M1",center:{x:-1.15,y:0},source_port_id:"source_port_1",facing_direction:"left",distance_from_component_edge:.4,pin_number:1,display_pin_label:"PWM",is_connected:false},
 {type:"schematic_port",schematic_port_id:"schematic_port_2",schematic_component_id:"schematic_M1",center:{x:1.15,y:0},source_port_id:"source_port_2",facing_direction:"right",distance_from_component_edge:.4,pin_number:2,display_pin_label:"GND",is_connected:false}
];
const project={projectId:"project-arm",objective:"make a robotic arm",revision:3,status:"ready",planningMode:"live_model",capability:{status:"SUPPORTED_WITH_LIMITATIONS",reasons:["Conceptual loads"]},representations:[{type:"circuit_schematic",artifactId:"circuit"}]};
const workItems=[
 {workItemId:"work-actuator",title:"Verify pitch actuator",description:"Confirm actuator capacity against panel load.",state:"in_progress",allowedTransitions:["paused","completed"],history:[{timestamp:"14:10",fromState:"planned",toState:"in_progress"}],relatedComponentIds:["component-shoulder-servo"],relatedRequirementIds:[],relatedFindingIds:["load"]},
 {workItemId:"work-sensor",title:"Finalize light sensor selection",state:"paused",allowedTransitions:["in_progress","abandoned"],reason:"Waiting for exact sensor specification.",history:[{timestamp:"14:45",fromState:"in_progress",toState:"paused",reason:"Waiting for exact sensor specification."}],relatedComponentIds:[],relatedRequirementIds:[],relatedFindingIds:[]},
 {workItemId:"work-electrical",title:"Electrical architecture",state:"completed",allowedTransitions:[],history:[],relatedComponentIds:["component-controller"],relatedRequirementIds:[],relatedFindingIds:[]},
];
async function mock(page:Page){
 await page.route("**/api/projects",r=>r.fulfill({json:[project]}));
 await page.route("**/api/projects/project-arm",r=>r.fulfill({json:project}));
 await page.route("**/api/projects/project-arm/revisions",r=>r.fulfill({json:[{revision:1,summary:"Project created"},{revision:2,summary:"Shoulder geometry refined"},{revision:3,summary:"Servo power path verified"}]}));
 await page.route("**/api/projects/project-arm/assembly",r=>r.fulfill({json:assembly}));
 await page.route("**/api/projects/project-arm/graph",r=>r.fulfill({json:graph}));
 await page.route("**/api/projects/project-arm/verification",r=>r.fulfill({json:{state:"warning",summary:{tool_verified:5,source_verified:3,cross_checked:2,estimated:4,conceptual:1,failed:0},findings:[{id:"load",category:"mechanical",check:"Actuator capability",state:"estimated",message:"Payload remains conceptual",entity_ids:["component-shoulder-servo"],evidenceIds:["evidence-servo"]}]}}));
 await page.route("**/api/projects/project-arm/evidence/evidence-servo",r=>r.fulfill({json:{evidenceId:"evidence-servo",publisher:"Servo Dynamics",document:"Actuator capability sheet",verifiedProperty:"Control interface",retrievedAt:"2026-08-22",status:"source_verified",sourceUrl:"https://example.com/servo"}}));
 await page.route("**/api/projects/project-arm/work-items",r=>r.fulfill({json:{items:workItems}}));
 await page.route("**/api/projects/project-arm/work",r=>r.fulfill({json:{items:workItems}}));
 await page.route("**/api/projects/project-arm/work-items/work-actuator/transitions",r=>r.fulfill({json:{...workItems[0],state:"paused",reason:"Awaiting verified panel mass.",history:[...workItems[0].history,{timestamp:"14:45",fromState:"in_progress",toState:"paused",reason:"Awaiting verified panel mass."}]}}));
 await page.route("**/api/projects/project-arm/work/work-actuator/transition",r=>r.fulfill({json:{...workItems[0],state:"paused",reason:"Awaiting verified panel mass.",history:[...workItems[0].history,{timestamp:"14:45",fromState:"in_progress",toState:"paused",reason:"Awaiting verified panel mass."}]}}));
 await page.route("**/api/projects/project-arm/scenarios",r=>r.fulfill({json:{scenarioId:"scenario-servo",baseRevisionId:3,changeSummary:"Replace shoulder servo with SG90 Micro Servo",changedIds:["component-shoulder-servo"],affectedIds:["component-upper-arm","component-controller"],verificationBefore:"pass",verificationAfter:"warn",confidenceBefore:"high",confidenceAfter:"medium",knownChanges:["Mount dimensions changed"],derivedImpacts:[{category:"mechanical",summary:"Actuator capability requires review",status:"estimated"},{category:"electrical",summary:"PWM-style control remains compatible",status:"cross_checked"}],uncertainties:["Required actuator torque is not yet verified."],applicable:true,stale:false}}));
 await page.route("**/api/projects/project-arm/scenarios/scenario-servo/commit",r=>r.fulfill({json:{revision:4}}));
 await page.route("**/api/projects/project-arm/narrations",r=>r.fulfill({json:[{narrationId:"n1",text:"The arm uses two low-voltage servo joints; mechanical load remains conceptual."}]}));
 await page.route("**/api/artifacts/circuit/content",r=>r.fulfill({json:schematic}));
}
const shot=(page:Page,name:string)=>page.screenshot({path:`../../../../../workspace/screenshots/goal11-correction/${name}.png`});

test("startup is an uncluttered engineering objective surface",async({page})=>{await page.setViewportSize({width:1920,height:1080});await page.goto("/");await expect(page.getByText("What do you want to build?")).toBeVisible();await expect(page.getByLabel("Describe an engineering system")).toHaveCount(1);await expect(page.locator("body")).not.toContainText("planning.live_model");await shot(page,"01-startup")});
test("desktop startup ignores the previously opened project and shows the planning switch",async({page})=>{await page.addInitScript(()=>{(window as any).auraDesktop={platform:"desktop",apiUrl:"",wsUrl:""};localStorage.setItem("aura:last-project","rc-car-project")});await page.goto("/");await expect(page.getByText("What do you want to build?")).toBeVisible();await expect(page.getByRole("switch",{name:"Online planning"})).toBeVisible();await expect(page).toHaveURL(/\/$/)});
test("launcher defaults offline and saves keyless cloud configuration from its top-right switch",async({page})=>{let submitted:any,saved:any;await page.route("**/api/projects",async route=>{if(route.request().method()!=="POST")return route.fulfill({json:[]});submitted=route.request().postDataJSON();return route.fulfill({status:422,json:{detail:{userMessage:"Offline requirement needs explicit components."}}})});await page.route("**/api/configuration/planning",async route=>{if(route.request().method()==="PUT")saved=route.request().postDataJSON();return route.fulfill({json:{projectId:saved?.projectId||"",configured:Boolean(saved),authenticated:Boolean(saved),adcProject:"",message:saved?"Google Application Default Credentials are connected.":"Run: gcloud auth application-default login"}})});await page.goto("/");const toggle=page.getByRole("switch",{name:"Online planning"});await expect(toggle).toHaveAttribute("aria-checked","false");await page.getByLabel("Planning options").click();await expect(page.getByTestId("planning-popover")).toContainText("No internet");await expect(page.getByTestId("planning-popover")).toContainText("Build a [system]");await page.getByLabel("Describe an engineering system").fill("Build an automatic irrigation system with a controller and pump");await page.getByRole("button",{name:"BUILD",exact:true}).click();await expect.poll(()=>submitted?.planningMode).toBe("deterministic_test");await expect(page.getByRole("status")).toContainText("Offline requirement needs explicit components.");await toggle.click();await expect(toggle).toHaveAttribute("aria-checked","true");await expect(page.getByTestId("planning-popover")).toContainText("never paste an API key");await page.getByLabel("Google Cloud project ID").fill("aura-demo-123");await page.getByRole("button",{name:"SAVE PROJECT"}).click();await expect.poll(()=>saved?.projectId).toBe("aura-demo-123");await expect(page.getByTestId("planning-popover")).toContainText("ADC CONNECTED")});
test("creating from the welcome surface hydrates the 3D scene without a reload",async({page})=>{await mock(page);await page.setViewportSize({width:1920,height:1080});await page.goto("/");await page.route("**/api/projects",route=>route.request().method()==="POST"?route.fulfill({status:201,json:project}):route.fulfill({json:[project]}));const objective=page.getByLabel("Describe an engineering system");await objective.fill("Make a robotic arm");await objective.press("Enter");await expect(page.getByTestId("engineering-space")).toBeVisible();await expect(page.locator("canvas")).toHaveCount(1);await page.waitForTimeout(700);const metrics=await page.evaluate(()=>(window as any).__auraSceneMetrics());expect(metrics.objects).toBe(parts.length);expect(metrics.triangles).toBeGreaterThan(0)});
test("3D dominates and rapid multi-surface selection remains stable",async({page})=>{await mock(page);await page.setViewportSize({width:1920,height:1080});await page.goto("/?projectId=project-arm");await expect(page.getByTestId("engineering-space")).toBeVisible();await page.waitForTimeout(700);await shot(page,"02-robotic-arm-completed");const count=await page.getByRole("button",{name:/component-/}).count();expect(count).toBe(8);for(let i=0;i<20;i++)await page.getByRole("button",{name:new RegExp(ids[i%ids.length])}).click();await expect(page.getByTestId("selected")).toHaveText(ids[3]);await page.waitForTimeout(5000);await expect(page.getByTestId("selected")).toHaveText(ids[3]);await page.getByRole("button",{name:/Shoulder servo component-shoulder-servo/}).click();await expect(page.getByTestId("part-info")).toContainText("Shoulder servo");await page.waitForTimeout(400);await shot(page,"03-selected-servo")});
test("useful assembly controls, verification and schematic remain functional",async({page})=>{await mock(page);await page.setViewportSize({width:1920,height:1080});await page.goto("/?projectId=project-arm");await expect(page.getByRole("button",{name:"EXPLODE"})).toBeVisible();await page.getByRole("button",{name:"EXPLODE"}).click();await shot(page,"04-robotic-arm-exploded");await page.getByRole("button",{name:/VERIFICATION/}).click();await expect(page.getByText("Engineering confidence")).toBeVisible();await shot(page,"05-verification-overlay");await page.getByLabel("Close verification").click();await page.getByRole("button",{name:"SCHEMATIC"}).click();await expect(page.getByTestId("schematic")).toBeVisible();await shot(page,"06-schematic");await page.getByRole("button",{name:"SPLIT"}).click();await shot(page,"07-split-assembly-schematic")});
test("one command surface previews, applies and preserves context",async({page})=>{await mock(page);await page.route("**/modification-proposals",r=>r.fulfill({status:201,json:{proposalId:"p1",summary:"Increase shoulder servo allowance",operations:[{path:"dimensions.width.value",oldValue:50,newValue:62}],affectedSemanticIds:["component-shoulder-servo"],unaffectedAreas:["controller"],artifactsToRegenerate:["repr-servo-3d"],verification:{checks:[{state:"PASSED",message:"Valid"}]}}}));await page.route("**/modification-proposals/p1/commit",r=>r.fulfill({json:{revision:4}}));await page.setViewportSize({width:1920,height:1080});await page.goto("/?projectId=project-arm");await page.getByRole("button",{name:/Shoulder servo component-shoulder-servo/}).click();const command=page.getByTestId("modification-request");await command.fill("Make the shoulder servo mount wider");await command.press("Enter");await expect(page.getByTestId("proposal-preview")).toBeVisible();await shot(page,"08-modification-preview");await page.getByTestId("apply-change").click();await expect(page.getByTestId("proposal-preview")).toHaveCount(0);await shot(page,"09-post-modification")});
test("normal mode hides diagnostics and viewport never scrolls",async({page})=>{await mock(page);await page.goto("/?projectId=project-arm");await expect(page.locator("body")).not.toContainText("operationId");expect(await page.evaluate(()=>({body:document.body.scrollHeight<=innerHeight,space:(document.querySelector('[data-testid=engineering-space]') as HTMLElement).scrollHeight<=(document.querySelector('[data-testid=engineering-space]') as HTMLElement).clientHeight}))).toEqual({body:true,space:true});await page.waitForTimeout(1200);const metrics=await page.evaluate(()=>(window as any).__auraSceneMetrics());console.log("AURA_SCENE_METRICS",metrics);expect(metrics.fps).toBeGreaterThan(30);expect(metrics.triangles).toBeGreaterThan(0)});
test("fan identity and paused live state remain visually restrained",async({page})=>{await mock(page);const fan={...parts[2],semanticId:"component-fan",label:"Temperature-controlled desk fan",subsystem:"actuator",dimensions:[90,30,90]};await page.route("**/api/projects/project-arm/assembly",r=>r.fulfill({json:{parts:[fan,{...parts[6]}],connectors:[],relationships:[]}}));await page.setViewportSize({width:1920,height:1080});await page.goto("/?projectId=project-arm");await shot(page,"extra-fan-completed")});
test("schematic camera remains user-owned through ten seconds of state changes",async({page})=>{await mock(page);await page.goto("/?projectId=project-arm");await page.getByRole("button",{name:"SPLIT"}).click();const camera=page.getByTestId("schematic-camera");await camera.hover();await page.mouse.wheel(0,-300);await page.mouse.move(1500,500);await page.mouse.down();await page.mouse.move(1600,570);await page.mouse.up();const transform=await camera.getAttribute("data-camera");for(let i=0;i<20;i++)await page.getByRole("button",{name:new RegExp(ids[i%ids.length])}).click();await page.getByRole("button",{name:"control signal"}).click();await page.getByRole("button",{name:/VERIFICATION/}).click();await page.waitForTimeout(10000);expect(await camera.getAttribute("data-camera")).toBe(transform)});
test("graph-owned schematic net selects endpoints without changing selection authority",async({page})=>{await mock(page);await page.goto("/?projectId=project-arm");await page.getByRole("button",{name:"SCHEMATIC"}).click();await page.getByRole("button",{name:"control signal"}).click();await expect(page.getByTestId("net-info")).toContainText("net-shoulder-control");await expect(page.getByTestId("net-info")).toContainText("ESP32 controller");await expect(page.getByTestId("net-info")).toContainText("signal");await expect(page.getByTestId("selected")).toHaveText("net-shoulder-control");await page.getByRole("button",{name:"SHOW ENDPOINTS IN 3D"}).click();await expect(page.getByTestId("engineering-space")).toHaveClass(/mode-assembly/)});
test("history and developer diagnostics remain contextual overlays",async({page})=>{await mock(page);await page.setViewportSize({width:1920,height:1080});await page.goto("/?projectId=project-arm");await page.getByRole("button",{name:"REV 03"}).click();await expect(page.getByTestId("history-panel")).toContainText("Servo power path verified");await page.screenshot({path:"../../../../../workspace/screenshots/goal11-correction/09-project-history.png"});await page.getByLabel("Close history").click();await page.getByLabel("Settings").click();await expect(page.getByText("DEVELOPER MODE")).toBeVisible();await page.screenshot({path:"../../../../../workspace/screenshots/goal11-correction/10-developer-mode.png"})});
test("label-free technical closeups retain component identity",async({page})=>{await mock(page);await page.setViewportSize({width:1920,height:1080});await page.goto("/?projectId=project-arm");for(const [label,name] of [["Shoulder servo","servo-joint"],["ESP32 controller","controller-board"],["Conceptual gripper","gripper"]]){await page.getByRole("button",{name:new RegExp(`${label} component-`)}).click();await page.getByRole("button",{name:"SHOW IN 3D"}).click();await page.waitForTimeout(300);await page.evaluate(()=>document.querySelectorAll(".topbar,.systems-rail,.contextual-inspector,.narration-card,.dock,.canvas-toolbar").forEach((element:any)=>element.style.visibility="hidden"));await page.screenshot({path:`../../../../../workspace/screenshots/goal11-correction/label-free-${name}.png`});await page.evaluate(()=>document.querySelectorAll(".topbar,.systems-rail,.contextual-inspector,.narration-card,.dock,.canvas-toolbar").forEach((element:any)=>element.style.visibility=""))}});

test("verification findings expose evidence without inventing provenance",async({page})=>{await mock(page);await page.goto("/?projectId=project-arm");await page.getByRole("button",{name:/VERIFICATION/}).click();await page.getByRole("button",{name:/Actuator capability/}).click();await expect(page.getByTestId("finding-info")).toContainText("Payload remains conceptual");await page.getByRole("button",{name:"OPEN"}).click();await expect(page.getByTestId("evidence-info")).toContainText("Servo Dynamics");await expect(page.getByTestId("evidence-info")).toContainText("SOURCE VERIFIED")});

test("work mode requires a persisted reason for pausing and renders history",async({page})=>{await mock(page);await page.setViewportSize({width:1366,height:768});await page.goto("/?projectId=project-arm");await page.getByRole("button",{name:"WORK",exact:true}).click();await expect(page.getByTestId("work-view")).toContainText("Verify pitch actuator");await page.getByTestId("work-item-work-actuator").click();const inspector=page.getByTestId("work-item-info");await expect(inspector).toContainText("PLANNED → IN PROGRESS");await inspector.getByRole("button",{name:"PAUSED",exact:true}).click();const dialog=page.getByRole("dialog");await expect(dialog.getByRole("button",{name:"PAUSED"})).toBeDisabled();await dialog.getByLabel("Reason *").fill("Awaiting verified panel mass.");await dialog.getByRole("button",{name:"PAUSED"}).click();await expect(dialog).toHaveCount(0);await expect(page.getByTestId("work-item-info")).toContainText("Awaiting verified panel mass.");await page.screenshot({path:"../../../../../workspace/screenshots/final-ui/05-work-paused-1366.png"})});

test("What-If keeps current state immutable until backend candidate apply",async({page})=>{await mock(page);await page.setViewportSize({width:1920,height:1080});await page.goto("/?projectId=project-arm");await page.getByRole("button",{name:/Shoulder servo component-shoulder-servo/}).click();await page.getByRole("button",{name:"WHAT IF?"}).click();await page.getByLabel("Candidate engineering change").fill("Replace with an SG90 Micro Servo");await page.getByRole("button",{name:"ANALYZE WITH AI"}).click();const scenarioPanel=page.getByTestId("scenario-info");await expect(scenarioPanel).toContainText("Actuator capability requires review");await expect(scenarioPanel).toContainText("HIGH");await expect(scenarioPanel).toContainText("MEDIUM");await page.getByRole("button",{name:"CANDIDATE"}).click();await page.screenshot({path:"../../../../../workspace/screenshots/final-ui/06-what-if-analysis.png"});await page.getByRole("button",{name:"DISCARD"}).click();await expect(page.getByTestId("scenario-info")).toHaveCount(0);await expect(page.getByRole("button",{name:"REV 03"})).toBeVisible()});

test("1366 desktop layout keeps artifact, hierarchy, inspector and command visible",async({page})=>{await mock(page);await page.setViewportSize({width:1366,height:768});await page.goto("/?projectId=project-arm");await page.getByRole("button",{name:/Shoulder servo component-shoulder-servo/}).click();for(const locator of [page.getByTestId("engineering-space"),page.locator(".systems-rail"),page.getByTestId("contextual-inspector"),page.getByTestId("modification-request")])await expect(locator).toBeVisible();const overflow=await page.evaluate(()=>({body:document.body.scrollWidth>innerWidth||document.body.scrollHeight>innerHeight,command:(document.querySelector(".dock") as HTMLElement).getBoundingClientRect().bottom>innerHeight}));expect(overflow).toEqual({body:false,command:false});await page.screenshot({path:"../../../../../workspace/screenshots/final-ui/07-component-inspector-1366.png"})});
