import {expect,test,APIRequestContext} from "@playwright/test";
const backend="http://127.0.0.1:4184";
async function project(r:APIRequestContext){const x=await r.post(`${backend}/api/projects`,{data:{objective:`Design a low voltage two axis robotic arm with servo actuators and controller for round two lifecycle ${crypto.randomUUID()}`,planningMode:"deterministic_test"}});expect(x.ok()).toBeTruthy();return x.json()}
async function work(r:APIRequestContext,p:string,title:string){const x=await r.post(`${backend}/api/projects/${p}/work`,{data:{title}});expect(x.ok()).toBeTruthy();return x.json()}

test("real workspace exposes Work creation and non-passive schematic zoom",async({page,request})=>{
 const errors:string[]=[];page.on("console",message=>{if(message.type()==="error")errors.push(message.text())});
 const p=await project(request);await page.goto(`${backend}/?projectId=${p.projectId}`);
 await expect(page.getByRole("button",{name:"WORK",exact:true})).toBeVisible();await page.getByRole("button",{name:"WORK",exact:true}).click();
 await expect(page.getByRole("button",{name:"ALL",exact:true})).toHaveClass(/active/);await expect(page.getByTestId("work-empty")).toContainText("No engineering work has been created for this project yet.");
 await page.getByRole("button",{name:"CREATE WORK ITEM"}).click();const create=page.getByRole("dialog");await create.getByLabel("Work item title").fill("Verify actuator capability");await create.getByLabel("Work item description").fill("Confirm actuator torque is sufficient.");await create.getByRole("button",{name:"CREATE",exact:true}).click();
 await expect(page.getByTestId("work-item-info")).toContainText("Verify actuator capability");await expect(page.getByTestId("work-item-info")).toContainText("Confirm actuator torque is sufficient.");await expect(page.getByTestId("work-view")).toContainText("1 PLANNED");
 await page.getByRole("button",{name:"SCHEMATIC",exact:true}).click();const camera=page.getByTestId("schematic-camera");await camera.hover();await page.mouse.wheel(0,-120);
 expect(errors.filter(value=>value.includes("passive event listener"))).toEqual([]);
});

test("real Work lifecycle enforces reasons, persists history, and updates summary",async({page,request})=>{
 const p=await project(request);await work(request,p.projectId,"Verify pitch actuator capability");await page.goto(`${backend}/?projectId=${p.projectId}`);await page.getByRole("button",{name:"WORK",exact:true}).click();await page.getByRole("button",{name:/Verify pitch actuator capability/}).click();let d=page.getByTestId("work-item-info");await d.getByRole("button",{name:"IN PROGRESS"}).click();await d.getByRole("button",{name:"PAUSED"}).click();const dialog=page.getByRole("dialog");await expect(dialog.getByRole("button",{name:"PAUSED"})).toBeDisabled();await dialog.getByRole("textbox").fill("Waiting for verified panel mass.");await dialog.getByRole("button",{name:"PAUSED"}).click();await page.reload();await page.getByRole("button",{name:"WORK",exact:true}).click();await page.getByRole("button",{name:/Verify pitch actuator capability/}).click();d=page.getByTestId("work-item-info");await expect(d).toContainText("PLANNED → IN PROGRESS");await expect(d).toContainText("IN PROGRESS → PAUSED");await d.getByRole("button",{name:"IN PROGRESS"}).click();await d.getByRole("button",{name:"COMPLETED"}).click();await expect(d).toContainText("COMPLETED");
 await work(request,p.projectId,"Enclosure design");await work(request,p.projectId,"Motor availability test");expect((await (await request.get(`${backend}/api/projects/${p.projectId}/work`)).json()).summary.total).toBe(3);
});

test("real What-If isolates, applies one represented revision, and rejects stale candidate",async({page,request})=>{
 const p=await project(request),g=await (await request.get(`${backend}/api/projects/${p.projectId}/graph`)).json(),target=g.entities.find((x:any)=>x.kind==="component"&&x.metadata?.family==="servo"),before=await (await request.get(`${backend}/api/projects/${p.projectId}`)).json();await page.goto(`${backend}/?projectId=${p.projectId}`);await expect(page.getByText("Select a component to explore an engineering change.")).toBeVisible();await page.getByRole("button",{name:new RegExp(target.id)}).click();await page.getByRole("button",{name:"WHAT IF?"}).click();await expect(page.locator(".scenario-target")).toContainText(target.name);await expect(page.getByRole("button",{name:"ANALYZE WITH AI"})).toBeDisabled();await page.getByLabel("Candidate engineering change").fill("Replace with Candidate Servo");await expect(page.getByRole("button",{name:"ANALYZE WITH AI"})).toBeEnabled();await page.getByRole("button",{name:"ANALYZE WITH AI"}).click();const panel=page.getByTestId("scenario-info");await expect(panel).toContainText("Candidate Servo");expect((await (await request.get(`${backend}/api/projects/${p.projectId}`)).json()).revision).toBe(before.revision);await panel.getByRole("button",{name:"DISCARD"}).click();
 const first=await (await request.post(`${backend}/api/projects/${p.projectId}/scenarios`,{data:{targetSemanticId:target.id,changeType:"REPLACE_COMPONENT",value:{name:"A"}}})).json(),second=await (await request.post(`${backend}/api/projects/${p.projectId}/scenarios`,{data:{targetSemanticId:target.id,changeType:"REPLACE_COMPONENT",value:{name:"B"}}})).json();expect((await request.post(`${backend}/api/projects/${p.projectId}/scenarios/${first.scenarioId}/apply`)).status()).toBe(404);const applied=await request.post(`${backend}/api/projects/${p.projectId}/scenarios/${second.scenarioId}/apply`);expect(applied.ok()).toBeTruthy();const result=await applied.json();expect(result.representations.some((x:any)=>x.revision===before.revision+1)).toBeTruthy();const stale=await (await request.post(`${backend}/api/projects/${p.projectId}/scenarios`,{data:{targetSemanticId:target.id,changeType:"REPLACE_COMPONENT",value:{name:"Stale"}}})).json(),newer=await (await request.post(`${backend}/api/projects/${p.projectId}/scenarios`,{data:{targetSemanticId:target.id,changeType:"REPLACE_COMPONENT",value:{name:"Newer"}}})).json();expect((await request.post(`${backend}/api/projects/${p.projectId}/scenarios/${newer.scenarioId}/apply`)).ok()).toBeTruthy();expect((await request.post(`${backend}/api/projects/${p.projectId}/scenarios/${stale.scenarioId}/apply`)).status()).toBe(404);
});

test("What-If uncertainty can become explicit planned engineering work",async({page,request})=>{
 const p=await project(request),g=await request.get(`${backend}/api/projects/${p.projectId}/graph`).then(r=>r.json()),target=g.entities.find((x:any)=>x.kind==="component"&&x.metadata?.family==="servo");await page.goto(`${backend}/?projectId=${p.projectId}`);await page.getByRole("button",{name:new RegExp(target.id)}).click();await page.getByRole("button",{name:"WHAT IF?"}).click();await page.getByLabel("Candidate engineering change").fill("Replace with Candidate Servo");await page.getByRole("button",{name:"ANALYZE WITH AI"}).click();await page.locator(".scenario-target").getByRole("button",{name:"CREATE WORK ITEM"}).click();await expect(page.getByTestId("engineering-space")).toHaveClass(/mode-work/);await expect(page.getByTestId("work-item-info")).toContainText("Verify Candidate Servo capability");const state=await request.get(`${backend}/api/projects/${p.projectId}/work`).then(r=>r.json());expect(state.summary.total).toBe(1);expect(state.items[0].state).toBe("PLANNED");
});

test("AI rejects a light sensor to servo substitution and keeps Apply disabled",async({page,request})=>{
 const created=await request.post(`${backend}/api/projects`,{data:{objective:`Build a tabletop two-axis solar tracker that automatically points a small solar panel toward the brightest light source using an Arduino Nano. ${crypto.randomUUID()}`,planningMode:"deterministic_test"}});expect(created.ok()).toBeTruthy();const p=await created.json(),g=await request.get(`${backend}/api/projects/${p.projectId}/graph`).then(r=>r.json()),sensor=g.entities.find((x:any)=>x.kind==="component"&&x.metadata?.family==="light_sensor");await page.goto(`${backend}/?projectId=${p.projectId}`);await page.getByRole("button",{name:new RegExp(`${sensor.id}$`)}).click();await page.getByRole("button",{name:"WHAT IF?"}).click();await page.getByLabel("Candidate engineering change").fill("Replace with servo");await page.getByRole("button",{name:"ANALYZE WITH AI"}).click();const panel=page.getByTestId("scenario-info");await expect(panel).toContainText("AI SEMANTIC REVIEW");await expect(panel).toContainText("DIRECT REPLACEMENT REJECTED");await expect(panel).toContainText("cannot provide ambient-light feedback");await expect(panel).toContainText("INCOMPATIBLE");await expect(panel.getByTestId("apply-scenario")).toBeDisabled();expect((await request.get(`${backend}/api/projects/${p.projectId}`).then(r=>r.json())).revision).toBe(p.revision);await page.screenshot({path:"test-results/aura-ai-scenario/light-sensor-servo-rejected.png",fullPage:true});
});
